//
//  CommentSectionWorker.swift
//  MBlogging
//
//  Created by Sujata Chakraborty on 29/09/2019.
//  Copyright (c) 2019 Sujata Chakraborty. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CommentSectionWorker : BaseWorkerClass
{
    var dataTask: URLSessionDataTask?
    
    
    /**
     Below request to fetch comment list from Server
     parameter 1:- base url : to fetch author list
     parameter 2:- authorID : pageNumber to to help pagination
     parameter 3:- authorID : authorid to get post details of specific author
     parameter 4:- sortOrder :Response will be sorted according to the SortOrder,currently Assumed it is ascending
     
     
     */
    func fetchComments(url : String , pageNumber : Int? , postId : String, sortOrder : SortOrder ,completionHandler: @escaping (_: [Comment]?, _: MBError?) -> Void)
    {
        
        let urlToRequest = createURLStringWith(baseUrl: url, sortOrder: sortOrder, requestForEntity: Constants.commentsURLParameter, queryString: "postId=\(postId)", pageIndexToBeFetched: pageNumber)
        
        if let urlToRequest = urlToRequest {
            
            dataTask =
                BaseWorkerClass.sessionManager.dataTask(with: urlToRequest) { [weak self] data, response, error in
                    defer {
                        self?.dataTask = nil
                    }
                    if let error = error {
                        
                        let mbError = MBError.init(mbErrorCode: MBErrorCode.ServerError)
                        mbError.mbErrorDebugInfo = error.localizedDescription + "problem with URL while fetching comment for post id \(postId)"
                        completionHandler(nil , mbError)
                        
                    } else if
                        let data = data,
                        let response = response as? HTTPURLResponse,
                        response.statusCode == 200 {
                        
                        DispatchQueue.main.async {
                            do
                            {
                                
                                let decoder = JSONDecoder()
                                let commentList = try decoder.decode([Comment].self, from: data)
                                
                                completionHandler(commentList , nil)
                                
                            }
                            catch let jsonErr {
                                
                                let mbError = MBError.init(mbErrorCode: MBErrorCode.UnableToParseErrorJson)
                                mbError.mbErrorDebugInfo = jsonErr.localizedDescription + "problem with URL while fetching comment for post id \(postId)"
                                completionHandler(nil , mbError)
                            }
                        }
                    }
                    else
                    {
                        let mbError = MBError.init(mbErrorCode: MBErrorCode.ServerError)
                        mbError.mbErrorDebugInfo = "Data issue in Comment list for post id \(postId)"
                        completionHandler(nil , mbError)
                    }
            }
            dataTask?.resume()
        }
        else
        {
            let mbError = MBError.init(mbErrorCode: MBErrorCode.GeneralError)
            mbError.mbErrorDebugInfo = "problem with URL while fetching request for Post list for author id \(postId)"
            completionHandler(nil , mbError)
        }
        
    }
    
    
    override func createURLStringWith(baseUrl : String , sortOrder : SortOrder , requestForEntity : String , queryString : String , pageIndexToBeFetched : Int?) -> URL?
    {
        let concatenatedURL = baseUrl + requestForEntity
        var orderQuery = fetchRequestQueryParameterFor(order: sortOrder)
        
        if let pageNumber = pageIndexToBeFetched
        {
            orderQuery = orderQuery +  "&" + "_page=" + String(pageNumber)
        }
        
        if var urlComponents = URLComponents(string: concatenatedURL) {
            urlComponents.query = queryString + "&" + orderQuery
            
            
            guard let urlToRequest = urlComponents.url else {
                
                return nil
            }
            
            return urlToRequest
            
        }
        
        return nil        
        
    }
}
