//
//  CommentSectionInteractor.swift
//  MBlogging
//
//  Created by Sujata Chakraborty on 29/09/2019.
//  Copyright (c) 2019 Sujata Chakraborty. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CommentSectionBusinessLogic
{
  func doSomething(request: CommentSection.Something.Request)
}

protocol CommentSectionDataStore
{
  //var name: String { get set }
}

class CommentSectionInteractor: CommentSectionBusinessLogic, CommentSectionDataStore
{
  var presenter: CommentSectionPresentationLogic?
  var worker: CommentSectionWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CommentSection.Something.Request)
  {
    worker = CommentSectionWorker()
    //worker?.doSomeWork()
    
    let response = CommentSection.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
