//
//  CommentSectionPresenter.swift
//  MBlogging
//
//  Created by Sujata Chakraborty on 29/09/2019.
//  Copyright (c) 2019 Sujata Chakraborty. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CommentSectionPresentationLogic
{
  func presentSomething(response: CommentSection.Something.Response)
}

class CommentSectionPresenter: CommentSectionPresentationLogic
{
  weak var viewController: CommentSectionDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CommentSection.Something.Response)
  {
    let viewModel = CommentSection.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
