//
//  AuthorPostDetailsInteractor.swift
//  MBlogging
//
//  Created by Sujata Chakraborty on 28/09/2019.
//  Copyright (c) 2019 Sujata Chakraborty. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorPostDetailsBusinessLogic
{
    func getAuthorDetails(request: AuthorPostDetails.FetchAuthorDetails.Request)
    func fetchPostDetails(request: AuthorPostDetails.FetchPostDetails.Request)
    
}

protocol AuthorPostDetailsDataStore
{
    var author: Author! { get set }

}

class AuthorPostDetailsInteractor: AuthorPostDetailsBusinessLogic, AuthorPostDetailsDataStore
{
    var author: Author!
    
    var presenter: AuthorPostDetailsPresentationLogic?
    var worker: AuthorPostDetailsWorker?
    //var name: String = ""
    
    
    
    // MARK: Responsibility of Interactor
    
    func getAuthorDetails(request: AuthorPostDetails.FetchAuthorDetails.Request)
    {
       
    }
    
    
    func fetchPostDetails(request: AuthorPostDetails.FetchPostDetails.Request)
    {
        
    }
    
//    func doSomething(request: AuthorPostDetails.Something.Request)
//    {
//        worker = AuthorPostDetailsWorker()
//        worker?.doSomeWork()
//        
//        let response = AuthorPostDetails.Something.Response()
//        presenter?.presentSomething(response: response)
//    }
}
