//
//  AuthorPostDetailsWorker.swift
//  MBlogging
//
//  Created by Sujata Chakraborty on 28/09/2019.
//  Copyright (c) 2019 Sujata Chakraborty. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AuthorPostDetailsWorker : BaseWorkerClass
{
    var dataTask: URLSessionDataTask?
    
    
    /**
     Below request to fetch author list from Server
     parameter 1:- base url : to fetch author list
     parameter 2:- authorID : authorid to get post details of specific author
     
     */
    func fetchPostDetails(url : String , authorID : String, order : SortOrder , completionHandler: @escaping (_: [Post]?, _: MBError?) -> Void)
    {
        
        let urlToRequest = createURLStringWith(baseUrl: url, sortOrder: order, requestForEntity: Constants.postURLParameter, queryString: "authorId=\(authorID)", pageIndexToBeFetched: nil)
        
        if let urlToReq = urlToRequest {
            
            dataTask =
                BaseWorkerClass.sessionManager.dataTask(with: urlToReq) { [weak self] data, response, error in
                    defer {
                        self?.dataTask = nil
                    }
                    if let error = error {
                        
                        let mbError = MBError.init(mbErrorCode: MBErrorCode.ServerError)
                        mbError.mbErrorDebugInfo = error.localizedDescription + "problem for post list for author id \(authorID)"
                        completionHandler(nil , mbError)
                        
                    } else if
                        let data = data,
                        let response = response as? HTTPURLResponse,
                        response.statusCode == 200 {
                        
                        DispatchQueue.main.async {
                            do
                            {
                                
                                let decoder = JSONDecoder()
                                let postList = try decoder.decode([Post].self, from: data)
                                
                                completionHandler(postList , nil)
                                
                            }
                            catch let jsonErr {
                                
                                let mbError = MBError.init(mbErrorCode: MBErrorCode.UnableToParseErrorJson)
                                mbError.mbErrorDebugInfo = jsonErr.localizedDescription + "problem for Post list for author id \(authorID)"
                                completionHandler(nil , mbError)
                            }
                        }
                    }
                    else
                    {
                        let mbError = MBError.init(mbErrorCode: MBErrorCode.ServerError)
                        mbError.mbErrorDebugInfo = "Data issue Post list for author id \(authorID)"
                        completionHandler(nil , mbError)
                    }
            }
            dataTask?.resume()
        }
        else
        {
            let mbError = MBError.init(mbErrorCode: MBErrorCode.GeneralError)
            mbError.mbErrorDebugInfo = "problem with URL while fetching request for Post list for author id \(authorID)"
            completionHandler(nil , mbError)
        }
        
    }
    
    
    override func createURLStringWith(baseUrl : String , sortOrder : SortOrder , requestForEntity : String , queryString : String? , pageIndexToBeFetched : Int?) -> URL?
    {
        let concatenatedURL = baseUrl + requestForEntity
        let orderQuery = fetchRequestQueryParameterFor(order: sortOrder)
        

        if var urlComponents = URLComponents(string: concatenatedURL) {
            
            if let queryString = queryString
            {
                urlComponents.query = queryString + "&" + orderQuery
                
            }
            else
            {
                urlComponents.query = orderQuery
            }
            
            
            guard let urlToRequest = urlComponents.url else {
                
                return nil
            }
            
            return urlToRequest
            
        }
        
        return nil
        
    }
    
    
    
    
}
