//
//  AuthorPostDetailsPresenter.swift
//  MBlogging
//
//  Created by Sujata Chakraborty on 28/09/2019.
//  Copyright (c) 2019 Sujata Chakraborty. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorPostDetailsPresentationLogic
{
    func presentAuthor(response:  AuthorPostDetails.FetchAuthorDetails.Response)

    func presentPostList(response: AuthorPostDetails.FetchPostDetails.Response)
}

class AuthorPostDetailsPresenter: AuthorPostDetailsPresentationLogic
{
  weak var viewController: AuthorPostDetailsDisplayLogic?
  
  // MARK: Do something
    
    func presentAuthor(response:  AuthorPostDetails.FetchAuthorDetails.Response)
    {
        
    }
    
    func presentPostList(response: AuthorPostDetails.FetchPostDetails.Response)
    {
        
    }
  
  
}
