//
//  AuthorPostDetailsRouter.swift
//  MBlogging
//
//  Created by Sujata Chakraborty on 28/09/2019.
//  Copyright (c) 2019 Sujata Chakraborty. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AuthorPostDetailsRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol AuthorPostDetailsDataPassing
{
    var dataStore: AuthorPostDetailsDataStore? { get }
}

class AuthorPostDetailsRouter: NSObject, AuthorPostDetailsRoutingLogic, AuthorPostDetailsDataPassing
{
    weak var viewController: AuthorPostDetailsViewController?
    var dataStore: AuthorPostDetailsDataStore?
    
    
}
