//
//  AuthorPostDetailsModels.swift
//  MBlogging
//
//  Created by Sujata Chakraborty on 28/09/2019.
//  Copyright (c) 2019 Sujata Chakraborty. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AuthorPostDetails
{
    // MARK: Use cases
    
    enum FetchPostDetails
    {
        struct Request
        {
            var authorId: String?
        }
        struct Response
        {
            var postList: [Post]?
            var error:    MBError?
        }
        struct ViewModel
        {
            
            struct DisplayedPost
            {
                var title: String
                var date:  String
                var body:  String
            }
            
            var postList: [DisplayedPost]
            
            
        }
    }
    
    enum FetchAuthorDetails
    {
        struct Request
        {
        }
        struct Response
        {
            var author : Author
        }
        struct ViewModel
        {
            struct DisplayAuthor
            {
                var id:        String
                var name:      String
                var userName:  String
                var email:     String
                var avatarUrl: String
            }
            var authorDetails: DisplayAuthor
            
        }
    }
}
