//
//  AuthorPostDetailsModels.swift
//  MBlogging
//
//  Created by Sujata Chakraborty on 28/09/2019.
//  Copyright (c) 2019 Sujata Chakraborty. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AuthorPostDetails
{
    // MARK: Use cases
    
    enum FetchPostDetails
    {
        struct Request
        {
        }
        struct Response
        {
            
        }
        struct ViewModel
        {
            
            struct DisplayedPost
            {
                
            }
            
            
            
        }
    }
    
    enum FetchAuthorDetails
    {
        struct Request
        {
        }
        struct Response
        {
            var author : Author
        }
        struct ViewModel
        {
            struct DisplayAuthor
            {
               
            }

        }
    }
}
