//
//  AuthorDetailsInteractor.swift
//  MBlogging
//
//  Created by Sujata Chakraborty on 27/09/2019.
//  Copyright (c) 2019 Sujata Chakraborty. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorDetailsBusinessLogic
{
  func doSomething(request: AuthorDetails.Something.Request)
}

protocol AuthorDetailsDataStore
{
  //var name: String { get set }
}

class AuthorDetailsInteractor: AuthorDetailsBusinessLogic, AuthorDetailsDataStore
{
  var presenter: AuthorDetailsPresentationLogic?
  var worker: AuthorDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: AuthorDetails.Something.Request)
  {
    worker = AuthorDetailsWorker()
    worker?.doSomeWork()
    
    let response = AuthorDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
