//
//  AuthorListModels.swift
//  MBlogging
//
//  Created by Sujata Chakraborty on 26/09/2019.
//  Copyright (c) 2019 Sujata Chakraborty. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


enum AuthorList
{
  // MARK: Use cases
  enum FetchAuthorList
  {
    struct Request
    {
        var pageNumber : Int = 0
        var urlToRequest : String = ""
        var sortOrder : SortOrder = .ascending

    }
    struct Response
    {
        var authors: [Author]?
        var error: MBError?
    }
    struct ViewModel
    {
        struct DisplayAuthorList
        {
            var name: String
            var userName: String
            var email: String
            var avatarUrl: String
        }
        var authorList: [DisplayAuthorList]
    }
  }
}
