//
//  AuthorListWorker.swift
//  MBlogging
//
//  Created by Sujata Chakraborty on 26/09/2019.
//  Copyright (c) 2019 Sujata Chakraborty. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AuthorListWorker : BaseWorkerClass
{
    var dataTask: URLSessionDataTask?
    
    
    /**
       Below request to fetch author list from Server
     parameter 1:- base url
     parameter 2:- page number to fetch(Every page contains 10 authors)
     
    */
    func fetchAuthorList(url: String, pageNumber : Int ,  completionHandler: @escaping (_: [Author]?, _: MBError?) -> Void)
    {
        var authorFectchUrl = url
        authorFectchUrl = authorFectchUrl + Constants.authorURLParameter
        
        if var urlComponents = URLComponents(string: authorFectchUrl) {
            urlComponents.query = "_page=\(pageNumber)"
            
            guard let url = urlComponents.url else {
                
                let mbError = MBError.init(mbErrorCode: MBErrorCode.GeneralError)
                mbError.mbErrorDebugInfo = "problem with URL while fetching request for Author list for page index \(pageNumber)"
                completionHandler(nil , mbError)
                return
            }
            dataTask =
                BaseWorkerClass.sessionManager.dataTask(with: url) { [weak self] data, response, error in
                    defer {
                        self?.dataTask = nil
                    }
                    if let error = error {
                        //need to handle error
                        
                        let mbError = MBError.init(mbErrorCode: MBErrorCode.ServerError)
                        mbError.mbErrorDebugInfo = error.localizedDescription + "problem for Author list for page index \(pageNumber)"
                        completionHandler(nil , mbError)
                        
                    } else if
                        let data = data,
                        let response = response as? HTTPURLResponse,
                        response.statusCode == 200 {
                        
                        DispatchQueue.main.async {
                            do
                            {
                                
                                let decoder = JSONDecoder()
                                let authorList = try decoder.decode([Author].self, from: data)
                                
                                completionHandler(authorList , nil)
                                
                            }
                            catch let jsonErr {
                                
                                let mbError = MBError.init(mbErrorCode: MBErrorCode.UnableToParseErrorJson)
                                mbError.mbErrorDebugInfo = jsonErr.localizedDescription + "problem for Author list for page index \(pageNumber)"
                                completionHandler(nil , mbError)
                            }
                        }
                    }
                    else
                    {
                        let mbError = MBError.init(mbErrorCode: MBErrorCode.ServerError)
                        mbError.mbErrorDebugInfo = "Data issue Author list for page index \(pageNumber)"
                        completionHandler(nil , mbError)
                    }
            }
            dataTask?.resume()
        }
        else
        {
            let mbError = MBError.init(mbErrorCode: MBErrorCode.GeneralError)
            mbError.mbErrorDebugInfo = "problem with URL while fetching request for Author list for page index \(pageNumber)"
            completionHandler(nil , mbError)
        }
        
    }
    
    
}
